services:
  final_auth_server:
    container_name: final_auth_server
    build: ./Server/Auth/
    ports:
      - "39899:39899"
    networks:
      - final-network
    env_file:
      - ./Server/Auth/.env
    environment:
      - REDIS_HOST=final_redis
      - MONGODB_HOST=final_mongo
      - MONGODB_PORT=27017
      - MONGODB_DATABASE_NAME=activity_tracking
    depends_on:
      final_redis:
        condition: service_healthy
      final_mongo:
        condition: service_started

  final_notification:
    build: ./Server/Notification
    image: notification:latest
    container_name: final_notification_server
    ports:
      - "39896:39896"
    env_file:
      - "./Server/Notification/.env"
    environment:
      - RABBITMQ_HOST=final_rabbitmq
      - RABBITMQ_PORT=5672
    depends_on:
      final_mongo:
        condition: service_started
      final_rabbitmq:
        condition: service_healthy
    networks:
      - final-network

  final_upload:
    build: ./Server/Upload
    image: upload:latest
    container_name: final_upload_server
    ports:
      - "39897:39897"
    env_file:
      - "./Server/Upload/.env"
    depends_on:
      final_auth_server:
        condition: service_started
    networks:
      - final-network

  final_rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:4.0.2
    ports:
      - "5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - final-network

  final_redis:
    container_name: final_redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - final-network
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 10s
      timeout: 5s
      retries: 3

  final_mongo:
    container_name: final_mongo
    image: mongodb/mongodb-community-server:latest
    ports:
      - "39990:27017"
    networks:
      - final-network

networks:
  final-network:
    name: final-network
