// mock-data.js

export const events = [
  {
    date: "2024-09-21",
    title: "Hội thảo du học và học bổng Hàn Quốc",
    time: "9:00 AM",
    location: "Hội trường C",
    description: "Du học, hội thảo",
    format: "Du học",
    attendees: 104,
    registered: false,
  },
  {
    date: "2024-09-21",
    title: "Seminar học thuật",
    time: "3:00 PM",
    location: "Hội trường C",
    description: "Seminar nghiên cứu, học thuật",
    format: "Seminar",
    attendees: 104,
    registered: true,
  },
  {
    date: "2024-10-05",
    title: "Hội thảo du học và học bổng Nhật Bản",
    time: "9:00 AM",
    location: "Hội trường A",
    description: "Du học, hội thảo",
    format: "Du học",
    attendees: 90,
    registered: false,
  },
  {
    date: "2024-10-10",
    title: "Hội thảo công nghệ blockchain",
    time: "2:00 PM",
    location: "Hội trường B",
    description: "Công nghệ, hội thảo",
    format: "Hội thảo",
    attendees: 150,
    registered: true,
  },
  {
    date: "2024-11-01",
    title: "Seminar ứng dụng AI trong y tế",
    time: "10:00 AM",
    location: "Hội trường C",
    description: "AI, y tế, hội thảo",
    format: "Seminar",
    attendees: 120,
    registered: false,
  },
  {
    date: "2024-11-15",
    title: "Hội thảo phát triển bền vững",
    time: "3:00 PM",
    location: "Hội trường D",
    description: "Môi trường, phát triển bền vững, hội thảo",
    format: "Hội thảo",
    attendees: 200,
    registered: true,
  },
  {
    date: "2024-12-01",
    title: "Seminar nghiên cứu vật liệu mới",
    time: "9:00 AM",
    location: "Hội trường A",
    description: "Vật liệu, nghiên cứu, seminar",
    format: "Seminar",
    attendees: 110,
    registered: false,
  },
  {
    date: "2024-12-10",
    title: "Hội thảo năng lượng tái tạo",
    time: "1:00 PM",
    location: "Hội trường E",
    description: "Năng lượng, tái tạo, hội thảo",
    format: "Hội thảo",
    attendees: 180,
    registered: true,
  },
  {
    date: "2025-01-05",
    title: "Seminar về trí tuệ nhân tạo",
    time: "11:00 AM",
    location: "Hội trường C",
    description: "AI, seminar, công nghệ",
    format: "Seminar",
    attendees: 140,
    registered: false,
  },
  {
    date: "2025-01-15",
    title: "Hội thảo khởi nghiệp sáng tạo",
    time: "3:00 PM",
    location: "Hội trường B",
    description: "Khởi nghiệp, hội thảo, sáng tạo",
    format: "Hội thảo",
    attendees: 160,
    registered: true,
  },
  {
    date: "2025-02-01",
    title: "Ngày hội việc làm tại trường",
    time: "9:00 AM",
    location: "Sân trường",
    description: "Tuyển dụng, việc làm",
    format: "Tại trường",
    attendees: 300,
    registered: false,
  },
  {
    date: "2025-02-15",
    title: "Triển lãm công nghệ mới",
    time: "10:00 AM",
    location: "Hội trường A",
    description: "Công nghệ, triển lãm",
    format: "Hội thảo",
    attendees: 220,
    registered: false,
  },
  {
    date: "2025-03-10",
    title: "Hội nghị quốc tế về năng lượng",
    time: "2:00 PM",
    location: "Hội trường B",
    description: "Năng lượng, hội nghị, quốc tế",
    format: "Hội nghị",
    attendees: 350,
    registered: true,
  },
  {
    date: "2025-03-25",
    title: "Hội thảo đào tạo kỹ năng mềm",
    time: "3:00 PM",
    location: "Phòng họp 101",
    description: "Kỹ năng mềm, đào tạo",
    format: "Hội thảo",
    attendees: 80,
    registered: false,
  },
  {
    date: "2025-04-01",
    title: "Tọa đàm về đổi mới giáo dục",
    time: "9:00 AM",
    location: "Hội trường D",
    description: "Giáo dục, đổi mới, tọa đàm",
    format: "Hội thảo",
    attendees: 90,
    registered: true,
  },
  {
    date: "2025-04-15",
    title: "Ngày hội sinh viên nghiên cứu khoa học",
    time: "11:00 AM",
    location: "Sân trường",
    description: "Nghiên cứu khoa học, sinh viên",
    format: "Tại trường",
    attendees: 400,
    registered: false,
  },
  {
    date: "2025-05-01",
    title: "Hội nghị chuyên đề về công nghệ AI",
    time: "10:00 AM",
    location: "Hội trường E",
    description: "AI, công nghệ, hội nghị",
    format: "Hội nghị",
    attendees: 500,
    registered: true,
  },
];