export const urlConfig = {
  AUTH: process.env.NEXT_PUBLIC_AUTH_SERVER,
  CORE: process.env.NEXT_PUBLIC_CORE_SERVER,
  NOTIFICATION: process.env.NEXT_PUBLIC_NOTIFICATION_SERVER,
  UPLOAD: process.env.NEXT_PUBLIC_UPLOAD_SERVER,
  OCR: process.env.NEXT_PUBLIC_OCR_SERVER,
};
